spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rentDB?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
  application:
    name: profile

#spring:     # asigna el perfil de la aplicacion, el valor esta inscrito en las propiedades de la aplicacion
 # application:
   # name: profile
  #jpa:   # crea automaticamente las tablas
   # hibernate:
security:
  oauth2:
    resource:
     token-info-uri: http://localhost:9191/oauth/check_token
    client:
      client-id: mobile
      client-secret: pin
server:
  port: 8181  # para sso video 013